compatibility_date = "2024-09-30"
compatibility_flags = [ "nodejs_compat" ]

name = "graficos-net"

main = ".output/server/index.mjs"

assets = { directory = ".output/public", binding = "ASSETS" }

[build]
command = "pnpm build"

[observability]
enabled = false
