compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

name = "graficos-net"

[observability]
enabled = true

[[d1_databases]]
binding = "D1"
database_name = "graficos_net_content"
database_id = "faee6a30-19c0-4808-8d89-aee0c61f41ca"
