compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_esm" ]

name = "graficos-net"

main = ".output/server/index.mjs"

base_dir = "."

assets = { directory = ".output/public", binding = "ASSETS" }

[build]
command = "pnpm build"

[observability.logs]
enabled = true
head_sampling_rate = 0.8
